---
# Note to self: Need to make sure when creating the template, the base OS have VMware Tools installed. Otherwise, the changing of network IP doesn't work.

# On the Ansible server, pre-requisite 
#  yum install python-pyvmomi

# yum install https://dl.fedoraproject.org/pub/epel/7/x86_64/Packages/e/epel-release-7-11.noarch.rpm

# To run playboook without host_key_checking, the command is as follows:
# ansible-playbook -i hosts -e 'host_key_checking=false' test.yml


- name: Create VMware guest
  hosts: all
  connection: local
  gather_facts: False
  vars_prompt:
    - name: "vcenter"
      prompt: "vCenter hostname?"
      default: "172.16.22.5"
      private: no
    - name: "user"
      prompt: "Enter vsphere username"
      default: "administrator@vsphere.local"
      private: no
    - name: "pass"
      prompt: "Enter vsphere password"
      private: yes
    - name: "esxi_hostname"
      prompt: "ESXi Hostname where the VM will run"
      default: "172.16.21.6"
      private: no
    - name: "datacenter"
      prompt: "Datacenter"
      default: "CX2"
      private: no
    - name: "datastore"
      prompt: "Datastore?"
      default: "HP_MSA2040_01_VM_Datastore_01"
      private: no
    - name: "vmname"
      prompt: "VM Name"
      default: "testvm"
      private: no
#    - name: "folder"
#      prompt: "Folder to store your VM"
#      default: "/Datacenter/datastore1/testvms/"
#      private: no
    - name: "template"
      prompt: "Template"
      default: "CentOS 7"
      private: no
    - name: "guestid"
      prompt: "Guest ID"
      default: "centos64Guest"
      private: no
    - name: "disk"
      prompt: "Disk Capacity GB"
      default: "20"
      private: no
    - name: "disktype"
      prompt: "Disk Type"
      default: "thin"
      private: no
    - name: "memory"
      prompt: "Memory Size (MB)"
      default: "1024"
      private: no
    - name: "cpu"
      prompt: "Number of CPU"
      default: "1"
      private: no
    - name: "vmip"
      prompt: "VM IP Address"
      default: "172.16.36.7"
      private: no      
    - name: "netmask"
      prompt: "Netmask"
      default: 255.255.255.0
      private: no
    - name: "gateway"
      prompt: "Gateway"
      default: "172.16.36.1"
      private: no
    - name: "dns"
      prompt: "DNS"
      default: "8.8.8.8"
      private: no
    - name: "devicetype"
      prompt: "Device Type"
      default: "vmxnet3"
      private: no
    - name: "vlan"
      prompt: "VLAN ID"
      default: "DS_Poc_DMZ_VLAN565"


  tasks:
  - name: Deploy guest from template
    vmware_guest:
      validate_certs: False
      hostname: "{{ vcenter }}"
      username: "{{ user }}"
      password: "{{ pass }}"
      datacenter: "{{ datacenter }}"
      cluster: "{{ cluster }}"
      name: "{{ vmname }}"
      state: poweredon
      template: "{{ template }}"
 #     guest_id: "{{ guestid }}"
      folder: Template/
      disk:
      - size_gb: "{{ disk }}"
#        type: "{{ disktype }}"
        datastore: "{{ datastore }}"
      hardware:
        memory_mb: "{{ memory }}"
        num_cpus: "{{ cpu }}"
        scsi: paravirtual
      networks:
      - name: VM Network
        ip: "{{ vmip }}"
        type: static
        netmask: "{{ netmask }}"
        gateway: "{{ gateway }}"
        dns_servers: "{{ dns }}"
        device_type: "{{ devicetype }}"
        vlan: "{{ vlan }}"
      customization:
        hostname: "{{ hostname }}"
# note: for hostname, do not insert domain. This will be added in the domain below.
        domain: "{{ my_domain }}"
      wait_for_ip_address: no
    delegate_to: localhost
    register: deploy
